// src/app/components/app-sidebar/app-sidebar.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, Router } from '@angular/router';
import {
  LucideAngularModule,
  Bus,
  LayoutDashboard,
  Route,
  Truck,
  Calendar,
  Clock,
  BarChart3,
  FileText,
  Settings,
  LogOut,
  PanelLeft
} from 'lucide-angular';
import {
  SidebarComponent,
  SidebarContentComponent,
  SidebarFooterComponent,
  SidebarHeaderComponent,
  SidebarMenuComponent,
  SidebarMenuItemComponent,
  SidebarMenuButtonComponent,
  SidebarProviderComponent
} from '../ui/sidebar/sidebar.component';
import { SidebarService } from '../../services/sidebar.service';

@Component({
  selector: 'app-sidebar-root',
  standalone: true,
  imports: [
    CommonModule,
    RouterLink,
    LucideAngularModule,
    SidebarComponent,
    SidebarContentComponent,
    SidebarFooterComponent,
    SidebarHeaderComponent,
    SidebarMenuComponent,
    SidebarMenuItemComponent,
    SidebarMenuButtonComponent,
    SidebarProviderComponent
  ],
  template: `
    <app-sidebar-provider>
      <app-sidebar>
        <app-sidebar-header class="border-b border-sidebar-border">
          <a routerLink="/dashboard" class="flex items-center gap-3 px-2 py-2">
            <div class="p-1.5 bg-primary rounded-lg">
              <lucide-icon [name]="Bus" class="h-5 w-5 text-primary-foreground"></lucide-icon>
            </div>
            <div class="flex flex-col">
              <span class="text-sm font-semibold">TransitAnalytics</span>
              <span class="text-xs text-muted-foreground">Delay Analytics</span>
            </div>
          </a>
        </app-sidebar-header>

        <app-sidebar-content>
          <div class="px-2 py-2 text-xs font-medium text-sidebar-foreground/70">Main</div>
          <app-sidebar-menu>
            <app-sidebar-menu-item *ngFor="let item of mainNavItems">
              <app-sidebar-menu-button [isActive]="router.url === item.href">
                <a [routerLink]="item.href" class="flex items-center gap-2 w-full">
                  <lucide-icon [name]="item.icon" class="h-4 w-4"></lucide-icon>
                  <span>{{item.title}}</span>
                </a>
              </app-sidebar-menu-button>
            </app-sidebar-menu-item>
          </app-sidebar-menu>

          <div class="px-2 py-2 mt-4 text-xs font-medium text-sidebar-foreground/70">Analytics</div>
          <app-sidebar-menu>
            <app-sidebar-menu-item *ngFor="let item of analyticsNavItems">
              <app-sidebar-menu-button [isActive]="router.url === item.href">
                <a [routerLink]="item.href" class="flex items-center gap-2 w-full">
                  <lucide-icon [name]="item.icon" class="h-4 w-4"></lucide-icon>
                  <span>{{item.title}}</span>
                </a>
              </app-sidebar-menu-button>
            </app-sidebar-menu-item>
          </app-sidebar-menu>

          <div class="px-2 py-2 mt-4 text-xs font-medium text-sidebar-foreground/70">System</div>
          <app-sidebar-menu>
            <app-sidebar-menu-item *ngFor="let item of systemNavItems">
              <app-sidebar-menu-button [isActive]="router.url === item.href">
                <a [routerLink]="item.href" class="flex items-center gap-2 w-full">
                  <lucide-icon [name]="item.icon" class="h-4 w-4"></lucide-icon>
                  <span>{{item.title}}</span>
                </a>
              </app-sidebar-menu-button>
            </app-sidebar-menu-item>
          </app-sidebar-menu>
        </app-sidebar-content>

        <app-sidebar-footer class="border-t border-sidebar-border">
          <app-sidebar-menu>
            <app-sidebar-menu-item>
              <app-sidebar-menu-button>
                <a routerLink="/login" class="flex items-center gap-2 w-full">
                  <lucide-icon [name]="LogOut" class="h-4 w-4"></lucide-icon>
                  <span>Sign Out</span>
                </a>
              </app-sidebar-menu-button>
            </app-sidebar-menu-item>
          </app-sidebar-menu>
        </app-sidebar-footer>
      </app-sidebar>

      <!-- Sidebar Inset equivalent -->
      <main class="bg-background relative flex w-full flex-1 flex-col">
        <header class="flex h-14 items-center gap-4 border-b bg-background px-6">
          <button (click)="sidebarService.toggleSidebar()" class="p-2 hover:bg-muted rounded-md md:hidden">
            <lucide-icon [name]="PanelLeft" class="h-5 w-5"></lucide-icon>
          </button>
          <div class="h-6 w-px bg-border hidden md:block"></div>
          <div class="flex-1">
            <h1 class="text-lg font-semibold">Public Transport Delay Analytics</h1>
          </div>
        </header>
        <div class="flex-1 overflow-auto bg-muted/30 p-6">
          <ng-content></ng-content>
        </div>
      </main>
    </app-sidebar-provider>
  `,
})
export class AppSidebarComponent {
  router = inject(Router);
  sidebarService = inject(SidebarService);

  readonly Bus = Bus;
  readonly LogOut = LogOut;
  readonly PanelLeft = PanelLeft;

  mainNavItems = [
    { title: "Dashboard", href: "/dashboard", icon: LayoutDashboard },
    { title: "Routes", href: "/dashboard/routes", icon: Route },
    { title: "Vehicles", href: "/dashboard/vehicles", icon: Truck },
    { title: "Schedules", href: "/dashboard/schedules", icon: Calendar },
    { title: "Arrival Logs", href: "/dashboard/arrivals", icon: Clock },
  ];

  analyticsNavItems = [
    { title: "Analytics", href: "/dashboard/analytics", icon: BarChart3 },
    { title: "Reports", href: "/dashboard/reports", icon: FileText },
  ];

  systemNavItems = [
    { title: "Settings", href: "/dashboard/settings", icon: Settings },
  ];
}

// src/components/app-sidebar.tsx
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import {
  Bus,
  LayoutDashboard,
  Route,
  Truck,
  Calendar,
  Clock,
  BarChart3,
  FileText,
  Settings,
  LogOut,
} from "lucide-react";
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarProvider,
  SidebarInset,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { Separator } from "@/components/ui/separator";

const mainNavItems = [
  {
    title: "Dashboard",
    href: "/dashboard",
    icon: LayoutDashboard,
  },
  {
    title: "Routes",
    href: "/dashboard/routes",
    icon: Route,
  },
  {
    title: "Vehicles",
    href: "/dashboard/vehicles",
    icon: Truck,
  },
  {
    title: "Schedules",
    href: "/dashboard/schedules",
    icon: Calendar,
  },
  {
    title: "Arrival Logs",
    href: "/dashboard/arrivals",
    icon: Clock,
  },
];

const analyticsNavItems = [
  {
    title: "Analytics",
    href: "/dashboard/analytics",
    icon: BarChart3,
  },
  {
    title: "Reports",
    href: "/dashboard/reports",
    icon: FileText,
  },
];

const systemNavItems = [
  {
    title: "Settings",
    href: "/dashboard/settings",
    icon: Settings,
  },
];

export function AppSidebar({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();

  return (
    <SidebarProvider>
      <Sidebar>
        <SidebarHeader className="border-b border-sidebar-border">
          <Link href="/dashboard" className="flex items-center gap-3 px-2 py-2">
            <div className="p-1.5 bg-primary rounded-lg">
              <Bus className="h-5 w-5 text-primary-foreground" />
            </div>
            <div className="flex flex-col">
              <span className="text-sm font-semibold">TransitAnalytics</span>
              <span className="text-xs text-muted-foreground">Delay Analytics</span>
            </div>
          </Link>
        </SidebarHeader>

        <SidebarContent>
          <SidebarGroup>
            <SidebarGroupLabel>Main</SidebarGroupLabel>
            <SidebarGroupContent>
              <SidebarMenu>
                {mainNavItems.map((item) => (
                  <SidebarMenuItem key={item.href}>
                    <SidebarMenuButton asChild isActive={pathname === item.href}>
                      <Link href={item.href}>
                        <item.icon className="h-4 w-4" />
                        <span>{item.title}</span>
                      </Link>
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                ))}
              </SidebarMenu>
            </SidebarGroupContent>
          </SidebarGroup>

          <SidebarGroup>
            <SidebarGroupLabel>Analytics</SidebarGroupLabel>
            <SidebarGroupContent>
              <SidebarMenu>
                {analyticsNavItems.map((item) => (
                  <SidebarMenuItem key={item.href}>
                    <SidebarMenuButton asChild isActive={pathname === item.href}>
                      <Link href={item.href}>
                        <item.icon className="h-4 w-4" />
                        <span>{item.title}</span>
                      </Link>
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                ))}
              </SidebarMenu>
            </SidebarGroupContent>
          </SidebarGroup>

          <SidebarGroup>
            <SidebarGroupLabel>System</SidebarGroupLabel>
            <SidebarGroupContent>
              <SidebarMenu>
                {systemNavItems.map((item) => (
                  <SidebarMenuItem key={item.href}>
                    <SidebarMenuButton asChild isActive={pathname === item.href}>
                      <Link href={item.href}>
                        <item.icon className="h-4 w-4" />
                        <span>{item.title}</span>
                      </Link>
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                ))}
              </SidebarMenu>
            </SidebarGroupContent>
          </SidebarGroup>
        </SidebarContent>

        <SidebarFooter className="border-t border-sidebar-border">
          <SidebarMenu>
            <SidebarMenuItem>
              <SidebarMenuButton asChild>
                <Link href="/login">
                  <LogOut className="h-4 w-4" />
                  <span>Sign Out</span>
                </Link>
              </SidebarMenuButton>
            </SidebarMenuItem>
          </SidebarMenu>
        </SidebarFooter>
      </Sidebar>

      <SidebarInset>
        <header className="flex h-14 items-center gap-4 border-b bg-background px-6">
          <SidebarTrigger />
          <Separator orientation="vertical" className="h-6" />
          <div className="flex-1">
            <h1 className="text-lg font-semibold">Public Transport Delay Analytics</h1>
          </div>
        </header>
        <main className="flex-1 overflow-auto bg-muted/30 p-6">
          {children}
        </main>
      </SidebarInset>
    </SidebarProvider>
  );
}
